// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ueekouycykwffgiyzlsp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVlZWtvdXljeWt3ZmZnaXl6bHNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MjA1NzksImV4cCI6MjA2OTk5NjU3OX0.2wsrOMOj1rfhbSR2LXGTJECtnjCnydnwhq8Es2-1V8g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});